### ISSUE TITLE
Skills

### ISSUE THREAD

**Issue by ghost** [dawncraft-modpack/ParaglidersStaminaCompats#1]
I can't configure the skill's stamina costs

**Comment by SettingDust** [comment]
Using datapack. See the basic attack for example

**Comment by ghost** [comment]
How do I configure stamina costs for things such as roll, guard, step, etc?

**Comment by SettingDust** [comment]
> How do I configure stamina costs for things such as roll, guard, step, etc?

See the data folder of epicfight.

**Comment by ghost** [comment]
whenenver I use a skill like roll/step holding a weapon, I use the skill stamina + the weapon cost stamina

example:
sword cost = 1
roll cost = 4
rolling while holding a sword = 5

is there a way to use a skill without adding the weapon's stamina cost that you are holding?

**Comment by SettingDust** [comment]
> whenenver I use a skill like roll/step holding a weapon, I use the skill stamina + the weapon cost stamina
> 
> example: sword cost = 1 roll cost = 4 rolling while holding a sword = 5
> 
> is there a way to use a skill without adding the weapon's stamina cost that you are holding?

As expected. No way. It's a XY problem. Why you need that?

**Comment by ghost** [comment]
I am just setting a modpack to play with my friends. I liked this mechanic
of "weapon categories" stamina cost that does not have in epic paragliders.
Particularly, it is a bit odd adding the dodge stamina cost to the weapon
stamina cost, i will keep trying alternative ways to balance the stamina
system in my modpack, but i am just telling you i find that, i dont know if
that is on purpose or not.
I know this mod is new and i admire you for your work. Sorry if i was
annoying.

Em sex., 24 de nov. de 2023 00:33, SettingDust ***@***.***>
escreveu:

**Comment by SettingDust** [comment]
Hmmm. Since you can set the skills stamina cost. The weapon categories cost can be lower to low impact. 
There isn't a better workaround to apply the weapon categories cost. Only apply to basic attack is a bit weird. And a heavier weapon consume more stamina when any action is making sense I think

**Comment by ghost** [comment]
Yeah, i talked to a friend and he said the same. I will do that, thank you.

Em sex., 24 de nov. de 2023 01:49, SettingDust ***@***.***>
escreveu:
