### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ghost** [dawncraft-modpack/ParaglidersStaminaCompats#2]
When I open some skill books, the game crashes, when i reload the world, all entities become invisible.
Mods: Epic Fight, Iron's spell, Weapons of minecraft, Paragliders, Paragliders Stamina Compats, Paragliders with Double Stamina

**Comment by SettingDust** [comment]
Crash should attach crash report

**Comment by SettingDust** [comment]
I think it's should be fixed. But you need attach crash report file to this issue
